"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { WorkspaceShell } from "../components/workspace-shell";

export default function ExplorerPage() {
  const [repository] = useState(() => typeof window === "undefined" ? "" : window.sessionStorage.getItem("engineering-memory:selected-repository") ?? ""); const [files, setFiles] = useState<string[]>([]); const [message, setMessage] = useState(repository ? "Loading repository files…" : "Import or select a repository to browse its indexed files.");
  useEffect(() => { if (!repository) return; fetch(`/api/github/tree?repository=${encodeURIComponent(repository)}`).then(async response => { const payload = await response.json() as { files?: string[]; message?: string }; if (!response.ok) throw new Error(payload.message); setFiles(payload.files ?? []); setMessage(""); }).catch(error => setMessage(error instanceof Error ? error.message : "Repository files could not be loaded.")); }, [repository]);
  return <WorkspaceShell eyebrow={repository ? `${repository} / source history` : "Repository / source history"} title="Repository explorer"><div className="explorer-toolbar"><div className="breadcrumbs"><strong>{repository || "No repository selected"}</strong></div><Link className="outline-action" href="/import">Import or switch repository</Link></div><section className="explorer-grid"><aside className="explorer-tree"><header><span>Repository files</span></header>{message ? <p className="tree-label">{message}</p> : <div className="file-tree">{files.map(file => <Link className="file-tree-item" href={`/codelore?question=${encodeURIComponent(`Why does ${file} exist?`)}`} key={file}><i>□</i>{file}</Link>)}</div>}<footer>{files.length ? `${files.length} files available` : "No files loaded"}</footer></aside><article className="explorer-timeline"><header><div><p className="section-kicker">Engineering investigation</p><h2>{repository ? "Select a file to ask why it exists." : "Start by importing a repository."}</h2></div></header><div className="event-stream"><p className="tree-label">File selection opens Codelore with a prefilled, evidence-led question. No sample repository events are displayed here.</p></div></article><aside className="evidence-panel"><header><div><p className="section-kicker">Next step</p><h2>Investigate</h2></div></header><section><p className="tree-label">Choose a file from the repository tree, then review its commits, pull requests, issues, and confidence in the investigation report.</p></section></aside></section></WorkspaceShell>;
}
