"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
interface GitHubRepository { id: number; fullName: string; url: string; description: string | null; private: boolean; }
export default function RepositoryPickerPage() {
  const router = useRouter(); const [repositories, setRepositories] = useState<GitHubRepository[]>([]); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/github/repositories").then(async response => { const payload = await response.json() as { repositories?: GitHubRepository[]; message?: string }; if (!response.ok) throw new Error(payload.message); setRepositories(payload.repositories ?? []); }).catch(error => setMessage(error instanceof Error ? error.message : "GitHub repositories could not be loaded.")).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => repositories.filter(repository => `${repository.fullName} ${repository.description ?? ""}`.toLowerCase().includes(query.toLowerCase())), [query, repositories]);
  async function select(repository: GitHubRepository) { setLoading(true); try { const response = await fetch("/api/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ repositoryUrl: repository.url }) }); const payload = await response.json() as { message?: string }; if (!response.ok) throw new Error(payload.message); router.push("/dashboard"); } catch (error) { setMessage(error instanceof Error ? error.message : "Repository import could not be started."); setLoading(false); } }
  return <main className="landing-shell"><section className="landing-workflow" style={{ paddingTop: 96 }}><div><p className="landing-kicker"><span /> GitHub repositories</p><h2>Choose a repository to investigate.</h2><p>Private repositories are available because you connected GitHub. You can also import public repositories without sign-in.</p></div><div><label className="context-field"><span>Search repositories</span><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by name or organization" /></label>{loading && <p>Loading repositories…</p>}{message && <p role="alert">{message}</p>}<div className="workflow-steps">{visible.map(repository => <button className="command-result" type="button" disabled={loading} onClick={() => select(repository)} key={repository.id}><span className="result-type">{repository.private ? "P" : "U"}</span><span className="result-copy"><strong>{repository.fullName}</strong><small>{repository.description ?? "No description"}</small></span><span className="result-kind">{repository.private ? "Private" : "Public"}</span></button>)}</div>{!loading && !message && visible.length === 0 && <p>No repositories match this search.</p>}</div></section></main>;
}
