import { WorkspaceShell } from "../components/workspace-shell";

const hotspots = [["src/auth.ts", "13", "High", "Authentication boundary"], ["src/middleware.ts", "11", "Medium", "Request orchestration"], ["src/cache/retry.ts", "9", "High", "Resilience policy"], ["src/logger.ts", "8", "Low", "Observability"]];

export default function InsightsPage() {
  return <WorkspaceShell eyebrow="Acme platform / engineering health" title="Repository insights">
    <section className="insight-hero"><div><p className="section-kicker">Health report / July</p><h2>The repository is <em>stable</em>, with three decisions worth protecting.</h2></div><div className="health-summary"><span>87</span><p><strong>Healthy</strong>+4 points from last month</p></div></section>
    <section className="insight-summary-grid"><article><span>Most modified</span><strong>auth.ts</strong><small>13 changes / 30 days</small></article><article><span>Dead areas</span><strong>04</strong><small>no references in 180 days</small></article><article><span>High-risk files</span><strong>03</strong><small>high churn or fragile dependencies</small></article><article><span>Oldest active module</span><strong>logger.ts</strong><small>introduced 2019 · still central</small></article></section>
    <section className="insight-detail-grid"><article className="panel hotspot-table"><header><div><p className="section-kicker">Engineering hotspots</p><h3>Files with the most decision pressure</h3></div><span>Last 30 days</span></header><div className="hotspot-head"><span>File</span><span>Changes</span><span>Risk</span><span>Role</span></div>{hotspots.map(([file, changes, risk, role]) => <div className="hotspot-row" key={file}><strong>{file}</strong><span>{changes}</span><b className={risk.toLowerCase()}>{risk}</b><small>{role}</small></div>)}</article><article className="panel architecture-map"><p className="section-kicker">Architecture pressure</p><h3>Dependency concentration</h3><div className="map-canvas"><span className="map-node auth">auth.ts <i>16</i></span><span className="map-node middleware">middleware.ts <i>9</i></span><span className="map-node api">api/session.ts <i>7</i></span><span className="map-node cache">retry.ts <i>4</i></span><b className="map-line line-one" /><b className="map-line line-two" /><b className="map-line line-three" /></div><p>auth.ts is the highest-leverage module. Its dependencies are clear, but its recent change frequency warrants review.</p></article></section>
    <section className="panel stale-panel"><header><div><p className="section-kicker">Stale & unowned</p><h3>Areas that may carry silent risk</h3></div></header><div className="stale-grid"><article><i>01</i><strong>src/cache/legacy.ts</strong><p>No direct references in 201 days. Last context: cache failover experiment.</p><span>Possible dead area</span></article><article><i>02</i><strong>docs/session-v1.md</strong><p>Contradicts the current edge-session model in two places.</p><span>Documentation drift</span></article><article><i>03</i><strong>src/logger.ts</strong><p>Central module with no decision record and one inactive owner.</p><span>Missing context</span></article></div></section>
  </WorkspaceShell>;
}
